# Generated by Django 3.1.4 on 2020-12-03 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StoreType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='ProductCategory',
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('contact_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('contact_street', models.CharField(blank=True, max_length=1024, null=True)),
                ('contact_zip', models.IntegerField(blank=True, null=True)),
                ('contact_location', models.CharField(blank=True, max_length=1024, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=1024, null=True)),
                ('contact_mobile', models.CharField(blank=True, max_length=1024, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('url', models.URLField()),
                ('certificates', models.ManyToManyField(to='store.Certificate')),
                ('languages', models.ManyToManyField(to='store.Language')),
                ('payments', models.ManyToManyField(to='store.Payment')),
                ('product_categories', models.ManyToManyField(to='store.ProductCategory')),
                ('production_type', models.ManyToManyField(to='store.ProductionType')),
                ('store_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.storecategory')),
                ('store_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.storetype')),
            ],
        ),
    ]
